spring:
  autoconfigure:
    exclude: org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
  ai:
    openai:
      api-key: helloWorld!ImJunhyung!

security:
  bcrypt:
    strength: 4

monitoring:
  resource-metrics:
    interval-ms: 1000 // 1초마다 로깅
