spring:
  autoconfigure:
    exclude: org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
  ai:
    openai:
      api-key: helloWorld!ImJunhyung!

security:
  bcrypt:
    strength: 4
